<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

$config['base_uri'] = 'https://emportalapi.qubesense.com/api/DataSync/GetJsonFormData';
$config['map'] = array(
    "surveys" => array(
        "row id" => "survey_id",
        "status" => "status",
        "user name" => "sbc_id",
        "meter recommendation" => "meter_recommendation",
        "location" => "gps_location_src",
        "meter type (make)" => "manufacturer",
        "current tarrif" => "existing_tariff_type",
        "recommanded tariff" => "recommended_tariff_type",
        "meter type required" => "meter_recommendation",
        "type of existing meter" => "existing_meter_type",
        "number of service wires" => "length_of_service_wires",
        "condition of service wire" => "condition_of_service_wire",
        "output cable distance (m)" => "cable_distance",
        "input cable distance (m)" => "cable_distance",
        "cable size (mm)" => "cable_size",
        "service wire traceable to meter point" => "service_wire_traceable_to_metering_point",
        "recommendations" => "meter_recommendation",
        "meter point wire distribution" => "meter_point_wire_distribution",
        "correction required by customer" => "correction_required_by_customer",
        "conclusion" => "remark",
        "total load" => "wattage",
        "total wattage" => "wattage",
    ),
    "customers" => array(
        "user name" => "sbc_id",
        "customer type" => "type",
        "customer name" => "name",
        "customer phone number" => "telephone",
        "customer address" => "address_description",
        "building owners name" => "landlord",
    ),
    "meters" => array(
        "account type" => "type",
        "account number" => "account_number",
        "old account number" => "old_account_number",
        "old meter number" => "meter_number",
        "split account no" => "parent_id",
        "meter number" => "meter_number",
        "current meter status" => "status",
    ),
    "orders" => array(
        "business unit" => "name",
        "undertaking" => "name",
        "dt name" => "name",
        "feeder" => "name",
        "no. of meter requires in location" => "quantity",
    ),
    "agents" => array(
        "sbc rep's  name" => "name",
    ),
    "business_units" => array(
        "business unit" => "name",
    ),
    "undertakings" => array(
        "undertaking" => "name",
    ),
    "transformers" => array(
        "dt name" => "name",
    ),
    "feeders" => array(
        "feeders" => "name",
    ),
    // "type of residence" => "type",
    // "external id" => "mbh-3",
    // "date" => "08/08/2018",
    // "picture of survey location front view" => "https => //www.ie-force.com/getimage.ashx?id=180808193430737000.jpg&formid=smat-ikja-pmis&formorderid=b2288e80-84fa-427b-8303-a9360130e79d",
    // "picture of customer bill" => "https => //www.ie-force.com/getimage.ashx?id=180808193507738000.jpg&formid=smat-ikja-pmis&formorderid=b2288e80-84fa-427b-8303-a9360130e79d",
    // "picture of existing meter point" => "https => //www.ie-force.com/getimage.ashx?id=180808193536139000.jpg&formid=smat-ikja-pmis&formorderid=b2288e80-84fa-427b-8303-a9360130e79d",
    // "picture of proposed meter point" => "https => //www.ie-force.com/getimage.ashx?id=180808193558043000.jpg&formid=smat-ikja-pmis&formorderid=b2288e80-84fa-427b-8303-a9360130e79d",
    // "picture of service wire from the pole" => "https => //www.ie-force.com/getimage.ashx?id=180808193616828000.jpg&formid=smat-ikja-pmis&formorderid=b2288e80-84fa-427b-8303-a9360130e79d",
    // "appliance" => "pressing iron",
    // "appliance type" => "dry iron",
    // "number" => "4",
    // "customer status" => "residential",
    // "dt capacity" => "500",
    // "installation type" => "wall",
    // "dt number" => "",
);
